_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ("fs_coco14_base_10_shot_train",)
  # TEST: ("fs_coco_test_all",)
  TEST: ("fs_coco17_base_val",)